// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD01zARgQBcMvPDKmQgqEdDzchpfXrpIeQ',
    appId: '1:213818068799:web:00753b49207db72ad34d8a',
    messagingSenderId: '213818068799',
    projectId: 'tailor-s',
    authDomain: 'tailor-s.firebaseapp.com',
    storageBucket: 'tailor-s.appspot.com',
    measurementId: 'G-G7RM3KBS0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-i2R4weWLMFSwFT1UL-8ZHUZv49ufmtI',
    appId: '1:213818068799:android:6e8f081236b43882d34d8a',
    messagingSenderId: '213818068799',
    projectId: 'tailor-s',
    storageBucket: 'tailor-s.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4cPX9ciGsiTEafiVeFXlRduKd3W_TJYI',
    appId: '1:213818068799:ios:4839963294f16df6d34d8a',
    messagingSenderId: '213818068799',
    projectId: 'tailor-s',
    storageBucket: 'tailor-s.appspot.com',
    iosBundleId: 'com.example.tailorSize',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4cPX9ciGsiTEafiVeFXlRduKd3W_TJYI',
    appId: '1:213818068799:ios:79155322378b5e22d34d8a',
    messagingSenderId: '213818068799',
    projectId: 'tailor-s',
    storageBucket: 'tailor-s.appspot.com',
    iosBundleId: 'com.example.tailorSize.RunnerTests',
  );
}
